import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const dist = fileURLToPath(new URL('../dist/', import.meta.url));

function filesUnder(folder) {
  return readdirSync(folder, { withFileTypes: true }).flatMap((entry) => {
    const path = join(folder, entry.name);
    return entry.isDirectory() ? filesUnder(path) : [path];
  });
}

const files = filesUnder(dist)
  .filter((file) => relative(dist, file) !== 'sw.js')
  .map((file) => relative(dist, file).replaceAll('\\', '/'))
  .sort();
const hash = createHash('sha256');
hash.update(readFileSync(fileURLToPath(import.meta.url)));
for (const file of files) {
  hash.update(file);
  hash.update(readFileSync(join(dist, file)));
}
const version = hash.digest('hex').slice(0, 12);
const sw = `// Generated from dist/ by scripts/generate-sw.mjs. Do not edit this file.
const CACHE = 'vatta-${version}';
const PRECACHE = ${JSON.stringify(files.map((file) => `./${file}`), null, 2)};
const PAGE_PATHS = new Set(['/', '/index.html', '/character-lab.html']);
const scope = new URL('./', self.location.href);

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys().then((keys) => Promise.all(
    keys.filter((key) => key.startsWith('vatta-') && key !== CACHE)
      .map((key) => caches.delete(key))
  )).then(() => self.clients.claim()));
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== scope.origin || !url.pathname.startsWith(scope.pathname)) return;
  const path = url.pathname.slice(scope.pathname.length);

  if (request.mode === 'navigate') {
    if (!PAGE_PATHS.has('/' + path)) return;
    event.respondWith(fetch(request).catch(async () => {
      const cache = await caches.open(CACHE);
      return cache.match(path === 'character-lab.html' ? './character-lab.html' : './index.html');
    }));
    return;
  }

  event.respondWith(caches.open(CACHE).then(async (cache) => {
    const cached = await cache.match(request);
    if (cached) return cached;
    const response = await fetch(request);
    // A tab can receive new HTML while its old worker is still active. Keep
    // newly fingerprinted assets available until the replacement worker takes over.
    if (path.startsWith('assets/') && response.ok) {
      await cache.put(request, response.clone());
    }
    return response;
  }));
});
`;
writeFileSync(join(dist, 'sw.js'), sw);
console.log(`service worker — ${files.length} files · ${version}`);
